site_name: DesiresAreGrey
site_description: "DesiresAreGrey's Website"
site_url: https://desiresaregrey.com/
theme:
  name: material
  logo: assets/DesiresAreGrey-Circle.png
  favicon: assets/DesiresAreGrey-Circle.png
  palette:
    scheme: slate
    primary: deep purple
    accent: indigo
  font:
    text: Inter
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  custom_dir: overrides
markdown_extensions:
  - attr_list
  - md_in_html
  - meta
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
plugins:
  - mkdocs-video
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      skip_classes:
       - no-lb
      auto_caption: false
      caption_position: bottom
  - minify:
      minify_css: true
      css_files:
        - stylesheets/extra.css
  - redirects:
      redirect_maps:
        '4transurvey2025/index.md': 'surveys/4tran2025/index.md'
        '4transurvey2025/2.md': 'surveys/4tran2025/2.md'
        '4transurvey2025/3.md': 'surveys/4tran2025/3.md'
        '4transurvey2025/4.md': 'surveys/4tran2025/4.md'
        '4transurvey2025/jealouscat.md': 'surveys/4tran2025/jealouscat.md'
        '4transurvey2025/ratgirltwink.md': 'surveys/4tran2025/ratgirltwink.md'
        'apex.md': 'misc/apex-weapon-stats/index.md'
        'apex-weapon-stats.md': 'misc/apex-weapon-stats/index.md'
extra:
  generator: false
  analytics:
    provider: google 
    property: G-67EDVX3WRV 
  social:
    - icon: fontawesome/brands/reddit-alien
      link: https://www.reddit.com/user/DesiresAreGrey
      name: Reddit
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/DesiresAreGrey
      name: Twitter
extra_css:
  - stylesheets/extra.css

exclude_docs: |
  csharp/

hooks:
  - 'scripts/misc/apex-weapon-stats/toc.py'
  - 'scripts/css-js-hasher.py'

nav:
  - Home: 'index.md'
  - Surveys:
    - 'surveys/index.md'
    - The 2025 4tran Survey: 
      - The 2025 4tran Survey: 'surveys/4tran2025/index.md'
      - The 2025 4tran Survey [Page 2]: 'surveys/4tran2025/2.md'
      - The 2025 4tran Survey [Page 3]: 'surveys/4tran2025/3.md'
      - The 2025 4tran Survey [Page 4]: 'surveys/4tran2025/4.md'
      - The 2025 4tran Survey [Jealous Cat]: 'surveys/4tran2025/jealouscat.md'
      - The 2025 4tran Survey [Ratgirltwink]: 'surveys/4tran2025/ratgirltwink.md'
#    - Extended 4tran Survey (2025.2): 
#      - Extended 4tran Survey (2025.2): 'surveys/4tran2025p2/index.md'
  - Misc:
    - 'misc/index.md'
    - Apex Legends Weapon Stats: 'misc/apex-weapon-stats/index.md'
    - Popular Modded Minecraft Versions: 'misc/modded-minecraft-versions.md'
    - .NET WebAssembly Test: 'misc/dotnet-wasm-test/index.md'
